### ISSUE TITLE
Initial state of imported jobs

### ISSUE THREAD

**Issue by TiSiE** [yawik/SimpleImport#1]
The initial status of imported jobs by a crawler must be configurable.

Currently they are imported as "Created", meaning the administrator has to approve every single job...

For some crawler this might not be the desired behaviour. So it must be possible to set the inital state per crawler.

**Comment by fedys** [comment]
Implemented in https://github.com/yawik/SimpleImport/commit/b0645766b3d089c5a9e52e2dca36d5bc9f9f53fd

**Comment by cbleek** [comment]
super. And I've updated http://yawik.readthedocs.io/en/latest/modules/simple-import/index.html
