### ISSUE TITLE
Use contactEmail (if provided) and no applyLink is present?

### ISSUE THREAD

**Issue by mbo-s** [yawik/SimpleImport#11]
At the moment the applymode is only set if an applyLink is provided

https://github.com/yawik/SimpleImport/blob/master/src/Hydrator/JobHydrator.php#L67-L71

from the spider docs, we could use the contactEmail
http://scrapy-docs.yawik.org/build/html/guidelines/format.html
> "contactEmail": "email address for applications (if available)",

is this correct?

**Comment by cbleek** [comment]
correct.

@kilip if a "contactEmail" is set, the applyMode should be set to email. The value of "contactEmail" soud be set as the email address

do you have time?
