### ISSUE TITLE
add-crawler does not check for existing crawlers

### ISSUE THREAD

**Issue by mbo-s** [yawik/SimpleImport#15]
The add-crawler command does not check for an existing crawler and will add the crawler twice

**Comment by cbleek** [comment]
@kilip

the following cli command adds a crawler to the db. The command should exit, if the name of the crawler already exists. 

`$ ./vendor/bin/yawik simpleimport add-crawler --name=mycrawler --feed-uri=http://example.com --organization=<valid organization id>`

do you have time do do this?

**Comment by kilip** [comment]
Yes, I will work on this issue now

**Comment by kilip** [comment]
@cbleek If necessary, I can make crawler to check an existing feed-uri too.

**Comment by cbleek** [comment]
Males more Sense, than to check the Spider Name. Yes, please Check The Feed-url.



Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361
60486 Frankfurt am Main  | Fax: 069-71910369
http://cross-solution.de | bleek@cross-solution.de
