### ISSUE TITLE
Use referenced documents for the crawler items.

### ISSUE THREAD

**Issue by TiSiE** [yawik/SimpleImport#17]
Mongo documents have a maximum size. 

Currently the crawler items (the meta data for a crawled job) are stored as embedded documents in the crawler entity. A crawler might be import a lot of jobs which could pose problems if we continue to embed the items.

So the items must be stored in a dedicated mongo collection and stored as referenced entities in the crawler entity.

**Comment by cbleek** [comment]
was fixed in https://github.com/yawik/SimpleImport/commit/e4a33b7470f55b344d5acdcdfcabd708c26305f7
