### ISSUE TITLE
Make run time period configurable

### ISSUE THREAD

**Issue by TiSiE** [yawik/SimpleImport#2]
After adding a crawler and then start the import process, this crawler does not run. 

1. A newly added crawler must immediatley be runnable.
2. The time period, in which the crawler is considered "already run" must be configurable.
    (for each crawler preferably, or at least globally)

**Comment by fedys** [comment]
Implemented in https://github.com/yawik/SimpleImport/commit/ba4f4098c009ec8247637c8f23af6e88dda7c1d3
