### ISSUE TITLE
Description in TemplateValues does not get imported

### ISSUE THREAD

**Issue by mbo-s** [yawik/SimpleImport#21]
Source looks like
```
{
      "templateValues": {
        "benefits": "<p>Content</p>",
        "requirements": "<p>Content</p>",
        "tasks": "<p>Content</p>",
        "description": "Companyname with Description"
      },
      "company": "Companyname",
      "location": "Germany",
      "title": "Jobtitle",
      "classifications": {
        "employmentTypes": "Vollzeit"
      },
      "link": "https://example.com/1351.html",
      "id": "1351"
    },
```

The Job is stored without description in the database, the other TemplateValues are stored correctly

**Comment by TiSiE** [comment]
Error is in InputFilter\JobDataInputFilter.php. "description" is not listed as valid key and is therefor discarded.

https://github.com/yawik/SimpleImport/blob/59ea06c51ce8232678c7ac6068c7d882f9029c33/src/InputFilter/JobDataInputFilter.php#L182-L204
