### ISSUE TITLE
Upgrade Geocoder

### ISSUE THREAD

**Issue by cbleek** [yawik/SimpleImport#31]
Version 3 requires egeloen/http-adapter, which id abandoned.

Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

**Comment by cbleek** [comment]
This branch contains the dependencies to use the geocoder 4.0
https://github.com/yawik/SimpleImport/tree/upgrade-geocoder

**Comment by cbleek** [comment]
@TiSiE can you check,?

**Comment by TiSiE** [comment]
Will be further dealt with in #35
