### ISSUE TITLE
 Fetching HTML source if no description is given

### ISSUE THREAD

**Issue by cbleek** [yawik/SimpleImport#4]
this was discussed in yawik/Solr#12

adding a jobosting without a fulltext to solr makes no sense. So what can we do, if a job is activated and no html is given.

My idea is to simply fetch the html. If fetching fails, the job is not inserted.

Can we/should we do this in the solr module?

Keep in mind that all the time consuming tasks like fetching pages, inserting into solr, sending mails... should be moved into some queing system

**Comment by fedys** [comment]
I will try to fetch the html during [inserting a new job](https://github.com/yawik/SimpleImport/blob/master/src/CrawlerProcessor/JobProcessor.php#L156). If that fails I have two options:
1. Not inserting a job at all?
2. Inserting a job but disallowing the **active** status (if such status is set in the given Crawler document) and setting some non-active status instead (e.g. **created** or **waiting for approval**)?

Where should be the html stored? JobInterface has no such field. Should I use the MetaDataProviderInterface::setMetaData() method with an `html` key for storing the fetched html?

**Comment by cbleek** [comment]
Hi Fedys,

Am 25.10.2017 um 10:15 schrieb Miroslav Fedeleš:
>
> I will try to fetch the html during inserting a new job. If that fails I have two options:
>
>     Not inserting a job at all?
>

I think, thats a good idea.

I assume, the cawler will try to fetch the job once again, if it started again.

>     Inserting a job but disallowing the active status (if such status is set in the given Crawler document) and setting some non-active status instead (e.g. created or waiting for approval)?
>
> Where should be the html stored? JobInterface has no such field. Should I use the MetaDataProviderInterface::setMetaData() method with an html key for storing the fetched html?

yes. But name the data "plaintext". We only need the the text of a jobad.

All HTML should be stripped. Including: <script>...</script>, <style>...</style>, <a>...</a>

regards, carsten

**Comment by fedys** [comment]
Implemented in https://github.com/yawik/SimpleImport/commit/a87010b02108a89ae8fbe19b778567eb934c0eb2

The following [PR](https://github.com/yawik/SimpleImport/commit/a87010b02108a89ae8fbe19b778567eb934c0eb2) is necessary for storing the fetched HTML in Solr.

**Comment by cbleek** [comment]
Hi Fedys,

I replaced the regex Code with with some Dom Lines because the regex leads to a "No Content" error:

`2017-10-29T10:52:53+01:00 ERR (3): Cannot fetch HTML digest for a job, import ID: "stellvertretende-filialleiterin-6", link: "https://www.spruengli.ch/cms/de/spruengli-welt/stellen-bei-spruengli/unsere-stellenangebote/unsere-stellenangebote-detail/jobController/Jobs/jobAction/detail/job/stellvertretende-filialleiterin-6/", reason: "No content"`

The Dom code is propably much more CPU expensive, but it's quite fail save. 

https://github.com/yawik/SimpleImport/commit/ddbd4bc5ab2b70da7ee2ac43b51a3b946a54bca7

Now it's working perfectly.

**Comment by fedys** [comment]
Hi Carsten,

I checked the regex and found out I made some mistakes. I forgot stop greediness signs and used bad quantifiers. I tried to parse the job [you noted](https://www.spruengli.ch/cms/de/spruengli-welt/stellen-bei-spruengli/unsere-stellenangebote/unsere-stellenangebote-detail/jobController/Jobs/jobAction/detail/job/stellvertretende-filialleiterin-6/) with fixes and it works as expected. You can see the fixes here https://github.com/yawik/SimpleImport/commit/306c216b9f285f356bd49efcd6942e0846c788ad.

As you can see there is also a possible bug in extracting content of the body tag. So you can use also Dom for body tag extraction or you can use the fixed regex ;)

**Comment by fedys** [comment]
Ok, I am with you, Dom is a better solution.
