### ISSUE TITLE
Geoencode locations

### ISSUE THREAD

**Issue by cbleek** [yawik/SimpleImport#6]
the SimpleImport module should be able to geoencode locations. http://geocoder-php.org/ can do the task but the latest version requires php7. 

But the older version 3.3  is working with php5.6

https://github.com/cbleek/geocoder-php-test

So the SimpleImport should be able create location objects with city, country, coods 

@TiSiE do you agree?

@fedys could you implement this?

**Comment by fedys** [comment]
I can implement that. I am too busy this week. I can take a look at it next Thursday.

**Comment by cbleek** [comment]
Thats ok.

**Comment by fedys** [comment]
@cbleek  I am working on it.

**Comment by fedys** [comment]
I have implemented that in https://github.com/yawik/SimpleImport/tree/geoencode
You have to run the following to load dependencies `composer require --dev yawik/simple-import` (version v0.0.5 should be installed with the Geoencode dependencies). Now it should be working. You can optionally replace /module/SimpleImport with the Git cloned one.

**Comment by cbleek** [comment]
where can I configure the google key? or is it currently nit possible?

**Comment by fedys** [comment]
You can do it via:
```php
return [
    'options' => [
        'SimpleImport/Options/Module' => [
            'options' => [
                'geocodeGoogleApiKey' => 'yourKey',
            ]
        ]
    ]
];
```

**Comment by cbleek** [comment]
works very good. Thanks
