### ISSUE TITLE
Cover code with unit tests

### ISSUE THREAD

**Issue by fedys** [yawik/SimpleImport#7]
Feel free to assign me this task.

**Comment by cbleek** [comment]
OK

**Comment by fedys** [comment]
I have just finished the unit tests with <a href='https://coveralls.io/github/yawik/SimpleImport?branch=unit-tests'><img src='https://coveralls.io/repos/github/yawik/SimpleImport/badge.svg?branch=unit-tests' alt='Coverage Status' /></a>.

**Comment by cbleek** [comment]
forgotten to close
