### ISSUE TITLE
Setting locations fails on updates.

### ISSUE THREAD

**Issue by TiSiE** [yawik/SimpleImport#8]
https://github.com/yawik/SimpleImport/blob/f917ac4183ccd064f488a107c029da2218abd740/src/Hydrator/JobHydrator.php#L60-L62

This works fine, if the job is a new entity, because __getLocations()__ returns an [__ArrayCollection__](https://github.com/cross-solution/YAWIK/blob/e2b04c46219a96ab6bce2f6b8041d44ffa678334/module/Core/src/Core/Entity/Collection/ArrayCollection.php). But it fails on persisted entities, because it returns a Doctrine __PersistentCollection__ then, which does not have the method __fromArray__.

Further on, even if this approach worked, it would _append_ the locations, not replace.

You probably want to simply set a new Collection of locations in any case:
`$job->setLocations(new ArrayCollection($locations))`

**Comment by fedys** [comment]
I had to use a different approach because setting `new ArrayCollection($locations)` does not affect existing jobs.

**Comment by cbleek** [comment]
perfect. Works now.

**Comment by fedys** [comment]
@TiSiE I tried `$job->setLocations(new ArrayCollection($locations))` and it works now. Strange, I had to overlook something before.

I also changed the logic a bit. Locations are always set now. In my opinion it makes sense.
