### ISSUE TITLE
Classifications import

### ISSUE THREAD

**Issue by fedys** [yawik/SimpleImport#9]
Include classifications into the import.

**Comment by fedys** [comment]
1. The following [PR](https://github.com/cross-solution/YAWIK/pull/444) has to be pulled to make it working.
2. I noticed the [import data](http://ftp.yawik.org/coop.json) has an invalid structure of the `classifications` key. There is an extra level.
3. In [/module/Jobs/src/Jobs/Form/ClassificationsFieldset.php#98](https://github.com/cross-solution/YAWIK/blob/9c12e7ded63775d57beffa8b8f16d71b16e642b8/module/Jobs/src/Jobs/Form/ClassificationsFieldset.php#L98) the `employmentTypes` is not a multiple value but it is defined as a multiple value in the [import format](http://scrapy-docs.yawik.org/build/html/guidelines/format.html). For now I have defined it as a multiple value in the SimpleImport module.

**Comment by cbleek** [comment]
forgotten to close
